version: '3.8'

services:
  
  # postgres:
    # container_name: cs-postgres
    # image: postgres:latest
    # hostname: localhost
    # ports:
        # - 5432:5432
    # environment:
        # - POSTGRES_PASSWORD=master
        
  # mysqldb:
    # container_name: mysqldb
    # image: mysql:latest
    # environment:
      # - MYSQL_ROOT_PASSWORD=my-secret-pw
    # restart: always
    # ports:
      # - 3306:3306
    # volumes:
      # - mysqldb:/var/lib/mysql      
  
  api:
    container_name: api-vacinacao
    image: api-vacinacao:latest
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080